# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='dcmt_author_2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='paper',
            name='dcmt_author_3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='paper',
            name='dcmt_author_4',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='paper',
            name='dcmt_author_5',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='paper',
            name='dcmt_author_6',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='paper',
            name='dcmt_author_7',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='paper',
            name='dcmt_author_8',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='paper',
            name='link',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
