# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20170624_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
